
CREATE TABLE IF NOT EXISTS users (
 id INT AUTO_INCREMENT PRIMARY KEY,
 email VARCHAR(255),
 password VARCHAR(255),
 role VARCHAR(20)
);

CREATE TABLE IF NOT EXISTS questions (
 id INT AUTO_INCREMENT PRIMARY KEY,
 test_id INT DEFAULT 1,
 text TEXT NOT NULL,
 type VARCHAR(20) DEFAULT 'choice'
);

CREATE TABLE IF NOT EXISTS answers (
 id INT AUTO_INCREMENT PRIMARY KEY,
 question_id INT NOT NULL,
 text VARCHAR(255) NOT NULL,
 is_correct TINYINT(1) DEFAULT 0,
 FOREIGN KEY (question_id) REFERENCES questions(id) ON DELETE CASCADE
);

CREATE TABLE IF NOT EXISTS results (
 id INT AUTO_INCREMENT PRIMARY KEY,
 user_id INT NOT NULL,
 question_id INT NOT NULL,
 answer_id INT DEFAULT NULL,
 correct TINYINT(1) DEFAULT 0,
 created_at DATETIME DEFAULT CURRENT_TIMESTAMP,
 FOREIGN KEY (user_id) REFERENCES users(id) ON DELETE CASCADE,
 FOREIGN KEY (question_id) REFERENCES questions(id) ON DELETE CASCADE,
 FOREIGN KEY (answer_id) REFERENCES answers(id) ON DELETE SET NULL
);

CREATE TABLE IF NOT EXISTS tests (
 id INT AUTO_INCREMENT PRIMARY KEY,
 title VARCHAR(255) NOT NULL,
 description TEXT,
 created_at DATETIME DEFAULT CURRENT_TIMESTAMP
);